basePath: /api/v1
definitions:
  contracts.RequestGanhos:
    properties:
      categoria:
        type: string
      data:
        type: string
      descricao:
        type: string
      observacao:
        type: string
      tipo:
        type: string
      usuario_id:
        type: integer
      valor:
        type: number
    type: object
  contracts.RequestGastos:
    properties:
      categoria:
        type: string
      data:
        type: string
      data_inicio:
        type: string
      descricao:
        type: string
      forma_pagamento:
        type: string
      observacao:
        type: string
      parcelas:
        type: integer
      usuario_id_created_at:
        type: integer
      usuario_id_updated_at:
        type: integer
      valor:
        type: number
    type: object
host: localhost:8085
info:
  contact:
    email: victor@email.com
    name: Victor Ramos
  description: API para gerenciamento financeiro pessoal
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: API Financeiro
  version: "1.0"
paths:
  /api/v1/ganhos:
    post:
      consumes:
      - application/json
      description: Cria um novo registro de ganho com os dados fornecidos no corpo
        da requisição
      parameters:
      - description: Dados do ganho a ser criado
        in: body
        name: ganho
        required: true
        schema:
          $ref: '#/definitions/contracts.RequestGanhos'
      produces:
      - application/json
      responses:
        "201":
          description: Ganho criado com sucesso
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Erro nos dados enviados
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno no servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo ganho
      tags:
      - Ganhos
  /api/v1/gastos:
    post:
      consumes:
      - application/json
      description: Cria um novo registro de gastos com os dados fornecidos no corpo
        da requisição
      parameters:
      - description: Dados do gasto a ser criado
        in: body
        name: gasto
        required: true
        schema:
          $ref: '#/definitions/contracts.RequestGastos'
      produces:
      - application/json
      responses:
        "201":
          description: Gasto criado com sucesso
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Erro nos dados enviados
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno no servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo gasto
      tags:
      - Gastos
  /ganhos/:
    get:
      consumes:
      - application/json
      description: Fetches a ganho record based List
      produces:
      - application/json
      responses:
        "200":
          description: Ganho retrieved successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid ID format
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Ganho not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve a ganho list
      tags:
      - Ganhos
  /ganhos/{id}:
    get:
      consumes:
      - application/json
      description: Fetches a ganho record based on the provided ID parameter
      parameters:
      - description: ID of the ganho to retrieve
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Ganho retrieved successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid ID format
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Ganho not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve a ganho by ID
      tags:
      - Ganhos
  /gastos/{id}:
    get:
      consumes:
      - application/json
      description: Fetches a gasto record based on the provided ID parameter
      parameters:
      - description: ID of the gasto to retrieve
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Gasto retrieved successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid ID format
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Gasto not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve a gasto by ID
      tags:
      - Gastos
swagger: "2.0"
